### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mrpwes** [TPEimperialPE/PlayTime#1]
add addons @ScoreHud plugin by Ifera.

add TopPlayTime that lists voters on your PocketMine-MP Server using FloatingTextParticles.

add config giving reward per time consume
console execute command per [ hr / mins ]  // rewards: items [ hr / mins ] <
```yml
config-version: 1
Type: cmd
   #cmd
   #rewards
Type2: simpleform
   #simpleform
   #modalform

##cmdsimpleform
CmdType: on
Time: hr #hr/mins
Time2: 1
   #if hr 1-24
   #if mins 1-60
command: givemoney {player} 50
##cmd simpleform player will receive stable reward 

##cmdmodalform
CmdType: off
Time: hr #hr/mins
Time2: 1
   #if hr 1-24
   #if mins 1-60
command: givemoney {player} 100
Time2: 2
   #if hr 1-24
   #if mins 1-60
command: givemoney {player} 200
Time2: 3
   #if hr 1-24
   #if mins 1-60
command: givemoney {player} 300
Time2: max
   #if max this is the maximum player can receive
   #if hr 1-24
   #if mins 1-60
command: givemoney {player} 400
##cmd modalform player will receive other reward per hour

##simplerewards
RewardType: off
Time: hr #hr/mins
Time2: 1
   #if hr 1-24
   #if mins 1-60
Items:
  - "260:0:10"
  - "267:0:10"
##rewards simpleform player will receive stable reward 

##modalformrewards
RewardType: off
Time: hr #hr/mins
Time2: 1
   #if hr 1-24
   #if mins 1-60
Items:
  - "260:0:10"
  - "267:0:10"
Time2: 2
   #if hr 1-24
   #if mins 1-60
Items:
  - "260:0:10"
  - "267:0:10"
Time2: max
   #if max this is the maximum player can receive
   #if hr 1-24
   #if mins 1-60
Items:
  - "260:0:10"
  - "267:0:10"
##rewards modalform player will receive other reward per hour
```
This is just a suggestion for a better future. ❤️❤️
